drop table  SYS_USER;
drop table  SYS_RESOURCE;
drop table  SYS_ROLE;
drop table SYS_DATA_DICTIONARY;
drop table  SYS_USER_AUTHORIZATION;
drop table  SYS_ROLE_AUTHORIZATION;
drop table SYS_USER_ROLE;

CREATE TABLE SYS_USER
(
STATUS CHAR(1) DEFAULT 'O' NOT NULL,
CREATED_BY  VARCHAR(80),
CREATED_DATE DATETIME,
LAST_UPDATED_BY VARCHAR(80),
LAST_UPDATED_DATE DATETIME,
USER_ACCOUNT CHAR(36) NOT NULL,
USER_NAME VARCHAR(80) NOT NULL,
USER_PASSWORD VARCHAR(200),
EMAIL_ADDR VARCHAR(200),
PHONE_NO VARCHAR(80),
ADDRESS VARCHAR(200),
FE_MALE CHAR(1) NULL,
FAIL_TIMES INT  DEFAULT 0 NOT NULL,
IS_LOCKED CHAR(1) DEFAULT 'N' NOT NULL ,
PRIMARY KEY (USER_ACCOUNT)
);

CREATE TABLE SYS_RESOURCE
(
STATUS CHAR(1)  DEFAULT 'O' NOT NULL,
CREATED_BY  VARCHAR(80),
CREATED_DATE DATETIME,
LAST_UPDATED_BY VARCHAR(80),
LAST_UPDATED_DATE DATETIME,
ID  CHAR(36)  NOT NULL,
RESOURCE_NAME VARCHAR(80),
RESOURCE_DESC VARCHAR(2000),
RESOURCE_TYPE CHAR(36)  DEFAULT 'WEB' NOT NULL,---/WEB/WFP_PAGE/WPF_WIN/WIN_FORM/CLASS/SERVICE/CONF/OPERATE/DATA/MENU
RESOURCE_SCOPE CHAR(36) DEFAULT 'GENERAL' NOT NULL ,---/GENERAL/PC/APP/PDA/KANBAN/REPORT
RESOURCE_LOCATION  VARCHAR(600) NOT NULL ,
PARENT_ID   VARCHAR(36),
PARENT_ID1  VARCHAR(36),
PARENT_ID2  VARCHAR(36),
PARENT_ID3  VARCHAR(36),
PARENT_ID4  VARCHAR(36),
PARENT_ID5  VARCHAR(36),
PARENT_ID6  VARCHAR(36),
RESOURCE_INDEX INT,
PRIMARY KEY (ID), 
CONSTRAINT SYS_RESOURCE$UNIQUE UNIQUE (RESOURCE_TYPE,RESOURCE_SCOPE,RESOURCE_LOCATION)
);

 
CREATE TABLE SYS_ROLE
 (
STATUS CHAR(1)  DEFAULT 'O' NOT NULL,
CREATED_BY  VARCHAR(80),
CREATED_DATE DATETIME,
LAST_UPDATED_BY VARCHAR(80),
LAST_UPDATED_DATE DATETIME,
ROLE_CODE CHAR(36) NOT NULL,
ROLE_NAME VARCHAR(80),
ROLE_DESC VARCHAR(2000),
PRIMARY KEY (ROLE_CODE)
 );

 
CREATE TABLE SYS_USER_AUTHORIZATION
(
STATUS CHAR(1)  DEFAULT 'O' NOT NULL,
CREATED_BY  VARCHAR(80),
CREATED_DATE DATETIME,
LAST_UPDATED_BY VARCHAR(80),
LAST_UPDATED_DATE DATETIME,
USER_ACCOUNT  CHAR(36)  NOT NULL,
RESOURCE_ID CHAR(36)  NOT NULL,
IS_FORBIDDEN CHAR(1)  DEFAULT 'N' NOT NULL,
PRIMARY KEY (USER_ACCOUNT,RESOURCE_ID)
);


CREATE TABLE SYS_ROLE_AUTHORIZATION
(
STATUS CHAR(1)  DEFAULT 'O' NOT NULL,
CREATED_BY  VARCHAR(80),
CREATED_DATE DATETIME,
LAST_UPDATED_BY VARCHAR(80),
LAST_UPDATED_DATE DATETIME,
ROLE_CODE CHAR(36)  NOT NULL,
RESOURCE_ID CHAR(36)  NOT NULL,
IS_FORBIDDEN CHAR(1) DEFAULT 'N' NOT NULL ,
PRIMARY KEY (ROLE_CODE,RESOURCE_ID)
);


CREATE TABLE SYS_USER_ROLE
(
STATUS CHAR(1)  DEFAULT 'O' NOT NULL,
CREATED_BY  VARCHAR(80),
CREATED_DATE DATETIME,
LAST_UPDATED_BY VARCHAR(80),
LAST_UPDATED_DATE DATETIME,
USER_ACCOUNT  CHAR(36)  NOT NULL,
ROLE_CODE CHAR(36)  NOT NULL,
PRIMARY KEY (USER_ACCOUNT,ROLE_CODE)
);


CREATE TABLE SYS_DATA_DICTIONARY
(
STATUS CHAR(1) DEFAULT 'O' NOT NULL ,
CREATED_BY  VARCHAR(80),
CREATED_DATE DATETIME,
LAST_UPDATED_BY VARCHAR(80),
LAST_UPDATED_DATE DATETIME,
TABLE_CODE  CHAR(36)  NOT NULL,
COLUMN_CODE CHAR(36)  DEFAULT '-' NOT NULL,
OBJ_NAME  VARCHAR(80),
OBJ_DESC  VARCHAR(2000) NULL,
ZHCN_NAME VARCHAR(80),
ENUS_NAME VARCHAR(80),
PRIMARY KEY (TABLE_CODE,COLUMN_CODE)
);



